language: node_js
node_js:
  - '8.10'
  - 'lts/*'

cache: yarn
script: npm test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install
